name: checkin_everyday

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: checkin_everyday
      env:
        JUEJIN_COOKIE: ${{ secrets.JUEJIN_COOKIE }}
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: npm ci && node checkIn.js "${JUEJIN_COOKIE}" "${PUSH_TOKEN}"
